runtime: python39
service: default

handlers:
  - url: /
    static_files: build/index.html
    upload: index.html
  - url: /(.*\.(gif|media|json|ico|eot|ttf|woff|woff2|png|jpg|css|js))$
    static_files: build/\1
    upload: (.*)
  - url: /(.*)
    static_files: build/index.html
    upload: index.html